---
- name: Remove Chrony if installed
  apt:
          name : chrony
          state: absent
  ignore_errors: yes

- name: Ensure systemd-timesyncd is installed
  apt:
          name: systemd-timesyncd
          state: present
          update_cache: yes

- name: Configure timesyncd
  template:
          src: timesyncd.conf.j2
          dest: /etc/systemd/timesyncd.conf
          owner: root
          group: root
          mode: '0644'
  notify: Restart timesyncd

- name: Set timezone
  timezone: 
     name: "{{ timesync_timezone }}"

- name: Enable and sart timesyncd
  systemd:
          name: systemd-timesyncd
          enabled: yes
          state: started 
